---
title: "Rで3億円宣言"
author: "Shinya Uryu"
date: 2016-12-01T00:00:00
categories: ["R", "poem", "advent_calendar"]
description:
    初日なのでエモい話。死ぬまでRで飯を食えたらいいねって今は思う
---

```{r setup, child = "../../_blog_post_declare.Rmd"}
```

初日なのでエモい話をしたいと思います。Rのコードは出てきません。完全にポエムです。明日からが一人Rアドベントカレンダーの本番だと思ってもらっても構いません。

...

私は今年3月から大学院をリタイアし、ｼｬｶｲｼﾞﾝとして働き出しました。

それから今日まで私が稼いできたお金は、自分自身のRを使った技術により稼いだものだと思っています。というのも私のｷﾞｮｰﾑ内容のほとんどはRを使った仕事だからです。なので給与はRで稼いだお金とほぼ等しいものとして考えます。

タイトルにある「Rで3億円宣言」というのは、**うまくいけば生涯で稼ぐであろう3億円を、Rによって稼いでやろう、Rの仕事を死ぬまで続けよう、R使いが増えるための環境構築や知見共有を行おう、という3つの宣言**です（ただし[某マニフェスト](https://github.com/tidyverse/tidyverse/blob/master/vignettes/manifesto.Rmd)のように、変わることもある、とここに書いておきます）。3億円まではまだまだ遠いけど、3億円に向けて今年大きな一歩を踏み出しました。月に向かうような話かもしれませんが、確実に歩み始めたのです。

## マニフェスト実現のための3ヵ条

マニフェストを実現するために、何をするべきでしょうか。雑に考えてみました。

### 1 Rを使える環境で働く

これは大事なことです。入社した会社はRを使える私を歓迎してくれました。Twitterでも同様の意見を得ましたが、ｼｬｶｲというのは結果が出せれば手段は問わない傾向にあるようです。Rを使ってデータベース操作、集計、データ分析に加え、そのほかｷﾞｮｰﾑを実行することに対して、何の問題もありませんでした。またShinyによるウェブアプリケーション開発も容認してくれ、**私のRに関する技術や知識はより実用的で幅広いものとなりました**。できればこのような良い環境を維持したいと思います。

### 2 Rについての情報を収集する・発信する

ニンジャにカラテが必要なように、Rユーザーも日々訓練が必要です。特にHadley Wickhamをはじめとしたタツジン級の開発者がRに関わるようになり、パッケージを含めた環境変化のスピードが速い近年では、すぐに技術は古くなってしまう気がしています。

小さな変更はすぐに追えますが、大きな変更や新しい技術を取得するのは難しいです。なので小さくコツコツ覚えていくのが良いでしょう。そのためには毎日Rと向き合い、情報を収集するのがてっとり早いと思います。また、情報は頭の中では成熟しませんので、コードを書くことが大事です。せっかく書いたのであれば、ブログやQiitaに記事を公開すると良いでしょう。副業が舞い込んでくるかもしれません（私自身はネットでの活動をきっかけにマイナビでの記事や本を書くことになりました）。

先日のJapan.Rでも、情報を発信する（生きている宣言をする）ことの大切さが語られました。私の場合、今年はブログを書く機会が去年までと比べて減ってしまったのですが、毎日Rには触れていましたし、GitHubでストーキングも続けていました。**死んでいるように見えても、先端技術について把握している自信があります**。

### 3 Rを好きであり続ける

もっとも大事な項目かもしれません。実を言うとRをここまで好きになったのはここ数年の出来事です。大学生時代は、植物を追いかけ、森に入っていたので、Rはここまで熱中できるものではありませんでした。将来についてもわかりません。上記2つの項目が実現できなくなって、Rに対する興味が薄れてしまうことも考えられます。ただ未来は不確実であることは確かです。もしそうなったらRのことは綺麗に忘れたいと思います。むしろ歓迎すべき事象だと受け入れるできです。**Rに飽きたということは多分、次に興味をもてる何かを見つけたということなのですから**。

...

## 一人Rアドベントカレンダーについて

今年、Rに触れ合う機会が豊富にあったにも関わらず、インターネットを介したアウトプットの少なさを反省して、**働き始めてから得たRやShinyの技術の整理として、Rに関するアドベントカレンダーを書くことにしました**。内容を考えていると、それが一つ二つでなく、多数あることに気がついたので、一人アドベントカレンダーをやろうと思いました。さらに、私の書きたい内容は次の5つに区分できることがわかったので、5種類の一人Rアドベントカレンダーを書きます。

1. **一人Rアドベントカレンダー**... Rに関する全般的な話題、パッケージの紹介などを予定
2. **一人Shinyアドベントカレンダー**... RのウェブアプリケーションフレームワークであるShinyに関するtipsや基本的な解説記事を予定
3. **一人Rパッケージ開発アドベントカレンダー**... Rのパッケージ作成に関する体験や話題を取り上げます
4. **一人visualizationアドベントカレンダー**... **`{ggplot2}`**や**`{plotly}`**といった可視化用パッケージに関する内容
5. **一人R + GISアドベントカレンダー**... ガチGISではなく、ゆるふわな感じでお送りします

正直毎日5つ書ける気はしないし、誰も完走することを期待していないでしょう。でもこれを書くのは自分のためです。他にも進捗を出すべき事案があるので、そちらを優先します。ほどほどにできたらなと思います。

余談ですが、この記事は[両側を中央線が走る、線路の真ん中に位置するカフェ](http://n3331.com)で、R界の神に近づきつつある、awesome ユタニーこと [yutannihilation](https://twitter.com/yutannihilation) を前にして書かれました。私のポエットなマニフェストとともに、進捗に付き合ってくれた彼に感謝の気持ちをここに表し、**3億円を稼いだあかつきには彼に寿司を献上することを誓います**。

## Rで3億円宣言

- Rを使った仕事で稼ぐ
- Rを使った仕事を継続させる
- Rで稼ぐための環境を作っていく

2016年12月1日
